version: "3.9"

services:
  vr_converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./converted_images:/app/converted_images
      - ./images:/app/images
      - ./static:/app/static
      - ./templates:/app/templates
    working_dir: /app
    command: python app.py
