version: "3.9"

services:
  vr_converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./converted_images:/app/converted_images
      - ./images:/app/images
      - ./static:/app/static
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - /run/udev:/run/udev:ro
    working_dir: /app
    command: python app.py
    devices:
      - "/dev/video0:/dev/video0"
    group_add:
      - "video"
